### ISSUE TITLE
While true 

### ISSUE THREAD

**Issue by zackprogrammer** [akionsight/Barcode_Generator#1]
in the while true part it breaks right after it did the code. Remove the while true remove indentions and u have less code. aint a bug buut trying to make ur code small.

**Comment by akionsight** [comment]
if you are talking about this while loop 
`
while True:
    event, values = window.read()

    if event in (None, 'OK'):
	
        text = values[0]

        break
`

it is important as without the while loop the PySimpleGUI window would disappear if the execution of the program would stop. Hence, to stop it the while loop is necessary and it also helps to read the various values from the window.
this can be understood as the `window.mainloop` in Tkinter
